# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'My Places' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift', '~>10'
  pod 'Cosmos', '~> 23.0'

  target 'My PlacesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'My PlacesUITests' do
    # Pods for testing
  end

end
